import NavbarDesktop from "@/components/Navigation/NavbarDesktop";
import "./globals.scss";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='pl'>
			<body>
				<NavbarDesktop />
				{children}
			</body>
		</html>
	);
}
